### ISSUE TITLE
ERRORs when using newest version on conda

### ISSUE THREAD

**Issue by xiekunwhy** [institut-de-genomique/HAPO-G#25]
Hi,

When I use newest HAPO-G version on conda, I got following errors
Traceback (most recent call last):
  File "/Bio/User/kxie/software/anaconda3/envs/hapog/bin/hapog", line 33, in <module>
    sys.exit(load_entry_point('hapog==1.3.4', 'console_scripts', 'hapog')())
  File "/Bio/User/kxie/software/anaconda3/envs/hapog/lib/python3.10/site-packages/hapog/cli.py", line 190, in main
    pipeline.launch_hapog(args.hapog_bin)
  File "/Bio/User/kxie/software/anaconda3/envs/hapog/lib/python3.10/site-packages/hapog/pipeline.py", line 172, in launch_hapog
    subprocess.Popen(
  File "/Bio/User/kxie/software/anaconda3/envs/hapog/lib/python3.10/subprocess.py", line 969, in \_\_init\_\_
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Bio/User/kxie/software/anaconda3/envs/hapog/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Bio/User/kxie/software/anaconda3/envs/hapog/lib/python3.10/site-packages/hapog_build/hapog'

Do you know why?

Best,
Kun

**Comment by bistace** [comment]
Hello,

it looks like the C binary `hapog` was not in your PATH, which is not supposed to happen (and does not happen in my tests) in the case of a conda installation. I am suspecting that a problem occured when the package was updated. Could you please try to completely remove and reinstall Hapo-g? You can do it like this:
```
# Make sure to be in the base conda env
conda remove --all -n hapog
conda create -n hapog
conda activate hapog
conda install -c bioconda hapog
```
